### ISSUE TITLE
win build seems slow compared to Linux?

### ISSUE THREAD

**Issue by squinkylabs** [VegaDeftwing/LyraeModules#2]
[LyraeModules-1.0.0-win.zip](https://github.com/VegaDeftwing/LyraeModules/files/7159098/LyraeModules-1.0.0-win.zip)

**Comment by VegaDeftwing** [comment]
Odd, I'm definitely not getting the same behavior. At 44.1khz VCO-1 with only a the sine out being used uses 2.3% of my CPU according to the built in meter, while Sulafat is using between 1.0 and 1.7% depending on the mode.

~~I wonder if this is a side effect of the complex SVG panel~~ nevermind, doesn't seem possible to be GPU related

I'm on Win10 21H1, have a Vega56 GPU and R9 3900x CPU, w/ 32Gb RAM on my desktop

Tested on my laptop as well, which has a 4k screen but a severely underpowered i7-7500U and Nvidia 940MX. Using the Nvdia or Intel graphics both gave the same results, and the difference in CPU (from high-end AMD desktop to low-power Intel Laptop) doesn't seem to have made a difference either. I'm wondering if maybe your CPU is older and lacks some relevant-to-performance floating point extension or maybe you're on Windows 7, 8.1, or 11?

**Comment by squinkylabs** [comment]
I'm on windows 10 with a decent but not screaming fast Xeon CPU:

Device name	DESKTOP-Q45DVE8
Processor	Intel(R) Xeon(R) E-2246G CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB
Device ID	173EA952-939D-446D-A5CF-5D5D6B15A27E
Product ID	00330-71412-38096-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

I don't think GPU should make a difference on the CPU meters - they doesn't measure any drawing stuff.

VCV and plugins don't use any extensions more recent than SSE2, which is like 12 years old

**Comment by squinkylabs** [comment]
here's a few more germane comparisons:

![image](https://user-images.githubusercontent.com/16314838/133366547-ef3f4b1f-9c6e-4f7d-8428-f8fc53b3e58f.png)

**Comment by VegaDeftwing** [comment]
How strange. I suppose we could go full GDB on it, but that would sort of require comparing your system to mine together. The other option I could think of is to use `perf`, but that's obviously linux exclusive and I don't know if you have a linux system setup on the same hardware.

The only other thing I can think of that might make a difference is something to do with audio drivers, so I went ahead and tested with everything from a block size of 64 to 2048, but that dosen't seem to matter either. I'm stumpped.

**Comment by VegaDeftwing** [comment]
Yeah, that is absolutely not what I'm seeing, either in Linux or Windows. I can't believe performance would be this variable

**Comment by VegaDeftwing** [comment]
hmmm, okay, one idea- it's a Xeon part which means it'll probably get microcode updates that go a little overkill on security, I wonder if an applied meltdown/spectre mitigation is making the branch predictor slow, so in that case it wouldn't be the `fmod` instructions but rather the switch statements.

running `grep . /sys/devices/system/cpu/vulnerabilities/*` in linux I get
```
/sys/devices/system/cpu/vulnerabilities/itlb_multihit:Not affected
/sys/devices/system/cpu/vulnerabilities/l1tf:Not affected
/sys/devices/system/cpu/vulnerabilities/mds:Not affected
/sys/devices/system/cpu/vulnerabilities/meltdown:Not affected
/sys/devices/system/cpu/vulnerabilities/spec_store_bypass:Mitigation: Speculative Store Bypass disabled via prctl and seccomp
/sys/devices/system/cpu/vulnerabilities/spectre_v1:Mitigation: usercopy/swapgs barriers and __user pointer sanitization
/sys/devices/system/cpu/vulnerabilities/spectre_v2:Mitigation: Full AMD retpoline, IBPB: conditional, STIBP: conditional, RSB filling
/sys/devices/system/cpu/vulnerabilities/srbds:Not affected
/sys/devices/system/cpu/vulnerabilities/tsx_async_abort:Not affected
```
so I have the mitigations on, but I wonder if for the Xeon part they're more aggressive?

**Comment by squinkylabs** [comment]
It's your use of std::sin. If I remove that the CPU usage gets ok:
![image](https://user-images.githubusercontent.com/16314838/133367146-2508789f-796b-4be6-9e9e-9da4ee565c92.png)

I mention that in this old paper: https://github.com/squinkylabs/Demo/blob/main/docs/efficient-plugins.md

**Comment by squinkylabs** [comment]
fwiw I benchmark a lot of "competing" plugins, and have never gotten results that seem crazy.

**Comment by VegaDeftwing** [comment]
ahh, okay, I'll switch it over to something more efficient in a coming release then. Thank you for tracking that down! I'm astounded that it would perform so variably on different hardware. Super interesting!

**Comment by squinkylabs** [comment]
yeah, I agree. It's one reason I like to write critical stuff myself - who knows what's in those libraries?

The VCV SDK has a decent sine approximation, I think they use it in Fundamental VCO-1. Mine worked out slightly better for me, but theirs is just fine. There are more details (way too many) about that in my really long paper about VCOs: https://github.com/squinkylabs/Demo/blob/main/demo-readme.md

**Comment by VegaDeftwing** [comment]
So I see in Fundamental VCO-1 he's using a 5th order approximation of sin as

```
return (T(-6.283185307) * x + T(33.19863968) * simd::pow(x, 3) - T(32.44191367) * simd::pow(x, 5))
	       / (1 + T(1.296008659) * simd::pow(x, 2) + T(0.7028072946) * simd::pow(x, 4));
```

but then Lfo-1, which is how I'm using sine, is using `simd::sin` outright, and doing a quick test LFO-1 appears to use less CPU than VCO-1 by about half, so I've just gone ahead with that. I've also replaced basically everything else I can with the provided simd library, which I imagine will help a bit too. I assume this is what you did to get the better performance above as well?

**Comment by squinkylabs** [comment]
Yes, simd::sin uses his approximation:
```
inline float_4 sin(float_4 x) {
	return float_4(sse_mathfun_sin_ps(x.v));
}

inline __m128 sse_mathfun_sin_ps(__m128 x) { // any x
	__m128 xmm1, xmm2 = _mm_setzero_ps(), xmm3, sign_bit, y;

	__m128i emm0, emm2;
	sign_bit = x;
	(etc.....)
```
As to what I do - no I don't think I usually use his approximations, but maybe sometimes?. But you can see exactly what I do If you read that whole document on how to make a VCO, which also shows how much faster mine is than Fundamental. Or look at the source for my BasicVCO.

FWIW, Fundamental VCO-1 is not a marvel of efficiency. It's pretty good / good enough, but you can see in the images I pasted above, or in that document, that my VCOs are much, much more efficient.

But, unless you are really obsessed with this (like I am), Anything VCV Fundamental modules do is pretty good - they make a good benchmark.
